package com.capgemini.MakeMyTrip.MakeMytripApplication;

import java.time.LocalTime;

public class FlightDetails {
	
	private static int flightIdAutoGenerated;
	
	private int flightId;
	private String flightName;
	private int flightFare;
	private LocalTime arrivalTime;
	private LocalTime departureTime;
	private String sourceCity;
	private String destinationCity;
	private int duration;
	
	
	
	
	
	public int getDuration() {
		return duration;
	}
	public void setDuration(int duration) {
		this.duration = duration;
	}
	
	public FlightDetails(String flightName, int flightFare, LocalTime arrivalTime, LocalTime departureTime,
			String sourceCity, String destinationCity, int duration) {
		super();
		flightId=flightIdAutoGenerated++;
		this.flightName = flightName;
		this.flightFare = flightFare;
		this.arrivalTime = arrivalTime;
		this.departureTime = departureTime;
		this.sourceCity = sourceCity;
		this.destinationCity = destinationCity;
		this.duration = duration;
	}
	public FlightDetails() {
		
		super();
		flightId=flightIdAutoGenerated++;
	}
	public String getFlightName() {
		return flightName;
	}
	public void setFlightName(String flightName) {
		this.flightName = flightName;
	}
	public int getFlightFare() {
		return flightFare;
	}
	public LocalTime getArrivalTime() {
		return arrivalTime;
	}
	public void setArrivalTime(LocalTime arrivalTime) {
		this.arrivalTime = arrivalTime;
	}
	public LocalTime getDepartureTime() {
		return departureTime;
	}
	public void setDepartureTime(LocalTime departureTime) {
		this.departureTime = departureTime;
	}
	public String getSourceCity() {
		return sourceCity;
	}
	public void setSourceCity(String sourceCity) {
		this.sourceCity = sourceCity;
	}
	public String getDestinationCity() {
		return destinationCity;
	}
	public void setDestinationCity(String destinationCity) {
		this.destinationCity = destinationCity;
	}
	public int getFlightId() {
		return flightId;
	}
	
	
	
	
	

}
